#ifndef GUARD_CONSTANTS_RESEARCH_H
#define GUARD_CONSTANTS_RESEARCH_H

#define RESEARCH_SAVE_VERSION                 0x5204
#define RESEARCH_MUTATION_CATEGORY_COUNT      8
#define RESEARCH_PROTO_LINE_COUNT             20
#define RESEARCH_RECENT_MUTATION_LOG_CAPACITY 8
#define RESEARCH_TIMESTAMP_UNKNOWN            0xFFFFFFFF
#define RESEARCH_LEVEL_UNKNOWN                0

#endif // GUARD_CONSTANTS_RESEARCH_H
