VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "My sister's POKéMON changed its\n"
	.string "nature overnight.\p"
	.string "The professor said it was\n"
	.string "impossible, but we all saw it happen.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "I swear, I saw it with my own eyes!$"

